# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tsdproxy-tsdproxy" = {
    image = "almeidapaulopt/tsdproxy:1";
    environment = {
      "HOME" = "/data";
    };
    volumes = [
      "/etc/tsdproxy:/config:rw"
      "/run/podman/podman.sock:/var/run/docker.sock:rw"
      "/run/secrets/tailscale_key:/run/secrets/tailscale_key:ro"
      "tsdproxy_datadir:/data:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tsdproxy"
      "--network=dawarich_dawarich"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-tsdproxy-tsdproxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tsdproxy_default.service"
      "podman-volume-tsdproxy_datadir.service"
    ];
    requires = [
      "podman-network-tsdproxy_default.service"
      "podman-volume-tsdproxy_datadir.service"
    ];
    partOf = [
      "podman-compose-tsdproxy-root.target"
    ];
    wantedBy = [
      "podman-compose-tsdproxy-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-tsdproxy_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tsdproxy_default";
    };
    script = ''
      podman network inspect tsdproxy_default || podman network create tsdproxy_default
    '';
    partOf = [ "podman-compose-tsdproxy-root.target" ];
    wantedBy = [ "podman-compose-tsdproxy-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-tsdproxy_datadir" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect tsdproxy_datadir || podman volume create tsdproxy_datadir
    '';
    partOf = [ "podman-compose-tsdproxy-root.target" ];
    wantedBy = [ "podman-compose-tsdproxy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tsdproxy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
