# ----------------------------------------------
# yorha light
# ----------------------------------------------

background #CDC9B3
foreground #3A342D
cursor #3A342D
selection_background #9D9589
selection_foreground #3A342D

color0  #CDC9B3
color8  #B8B29D
color1  #8B5A54
color9  #9A6B65
color2  #7A8B54
color10 #899A65
color3  #8B7A54
color11 #9A8965
color4  #547A8B
color12 #658999
color5  #8B547A
color13 #9A6589
color6  #548B7A
color14 #659A89
color7  #4A443B
color15 #3A342D

active_tab_background #7A7468
active_tab_foreground #CDC9B3
inactive_tab_background #B8B29D
inactive_tab_foreground #5A544A
