# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."rudolfs" = {
    image = "jasonwhite0/rudolfs:latest";
    volumes = [
      "/var/lib/rudolfs/cache:/data:rw"
      "/var/lib/rudolfs/storage:/storage:rw"
    ];
    cmd = [
      "--host=0.0.0.0:8080"
      "--cache-dir=/data"
      "--max-cache-size=20GiB"
      "local"
      "--path=/storage"
    ];
    labels = {
      "tsdproxy.container_port" = "8080";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "rudolfs";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=rudolfs"
      "--network=rudolfs_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-rudolfs" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-rudolfs_default.service"
    ];
    requires = [
      "podman-network-rudolfs_default.service"
    ];
    partOf = [
      "podman-compose-rudolfs-root.target"
    ];
    wantedBy = [
      "podman-compose-rudolfs-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-rudolfs_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f rudolfs_default";
    };
    script = ''
      podman network inspect rudolfs_default || podman network create rudolfs_default
    '';
    partOf = [ "podman-compose-rudolfs-root.target" ];
    wantedBy = [ "podman-compose-rudolfs-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-rudolfs-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
