# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."homebox" = {
    image = "ghcr.io/sysadminsmedia/homebox:latest";
    environment = {
      "HBOX_LOG_FORMAT" = "text";
      "HBOX_LOG_LEVEL" = "info";
      "HBOX_WEB_MAX_UPLOAD_SIZE" = "10";
    };
    volumes = [
      "/var/lib/homebox/data:/data:rw"
    ];
    ports = [
      "3100:7745/tcp"
    ];
    labels = {
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "inventory";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=homebox"
      "--network=homebox_default"
    ];
  };
  systemd.services."podman-homebox" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-homebox_default.service"
    ];
    requires = [
      "podman-network-homebox_default.service"
    ];
    partOf = [
      "podman-compose-homebox-root.target"
    ];
    wantedBy = [
      "podman-compose-homebox-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-homebox_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f homebox_default";
    };
    script = ''
      podman network inspect homebox_default || podman network create homebox_default
    '';
    partOf = [ "podman-compose-homebox-root.target" ];
    wantedBy = [ "podman-compose-homebox-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-homebox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
