services:
  silverbullet:
    image: zefhemel/silverbullet:2.6.1
    container_name: silverbullet
    volumes:
      - /home/vessel/Enchiridion:/space
    ports:
      - "3000:3000"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "enchiridion"
      tsdproxy.container_port: "3000"
    restart: unless-stopped

  # read-only instance thru cloudflare zero-trust (access controlled by email)
  # https://community.silverbullet.md/t/use-silverbullet-with-cloudflare-zero-trust/3618
  silverbullet-read:
    image: zefhemel/silverbullet:2.6.1
    container_name: silverbullet-read
    volumes:
      - /home/vessel/Enchiridion:/space:ro
    ports:
      - "3001:3000"
    restart: unless-stopped
    environment:
      - SB_READ_ONLY=true
