# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."silverbullet" = {
    image = "zefhemel/silverbullet@sha256:4b819510519322df146d9c51e937718f7f52a97ad24291ee3e7d7ce02231d45f";
    volumes = [
      "/home/vessel/Enchiridion:/space:rw"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    labels = {
      "tsdproxy.container_port" = "3000";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "enchiridion";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=silverbullet"
      "--network=silverbullet_default"
    ];
  };
  systemd.services."podman-silverbullet" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-silverbullet_default.service"
    ];
    requires = [
      "podman-network-silverbullet_default.service"
    ];
    partOf = [
      "podman-compose-silverbullet-root.target"
    ];
    wantedBy = [
      "podman-compose-silverbullet-root.target"
    ];
  };
  virtualisation.oci-containers.containers."silverbullet-read" = {
    image = "zefhemel/silverbullet@sha256:4b819510519322df146d9c51e937718f7f52a97ad24291ee3e7d7ce02231d45f";
    environment = {
      "SB_INDEX_PAGE" = "\"Welcome\"";
      "SB_READ_ONLY" = "true";
    };
    volumes = [
      "/home/vessel/Enchiridion:/space:ro"
    ];
    ports = [
      "3001:3000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=silverbullet-read"
      "--network=silverbullet_default"
    ];
  };
  systemd.services."podman-silverbullet-read" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-silverbullet_default.service"
    ];
    requires = [
      "podman-network-silverbullet_default.service"
    ];
    partOf = [
      "podman-compose-silverbullet-root.target"
    ];
    wantedBy = [
      "podman-compose-silverbullet-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-silverbullet_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f silverbullet_default";
    };
    script = ''
      podman network inspect silverbullet_default || podman network create silverbullet_default
    '';
    partOf = [ "podman-compose-silverbullet-root.target" ];
    wantedBy = [ "podman-compose-silverbullet-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-silverbullet-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
