# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "fallenbagel/jellyseerr:latest";
    environment = {
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/jellyseerr/config:/app/config:rw"
    ];
    labels = {
      "tsdproxy.container_port" = "5055";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "requests";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyseerr"
      "--network=arr_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-jellyseerr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arr_default.service"
    ];
    requires = [
      "podman-network-arr_default.service"
    ];
    partOf = [
      "podman-compose-arr-root.target"
    ];
    wantedBy = [
      "podman-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/prowlarr/config:/config:rw"
    ];
    labels = {
      "tsdproxy.container_port" = "9696";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "prowlarr";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prowlarr"
      "--network=arr_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arr_default.service"
    ];
    requires = [
      "podman-network-arr_default.service"
    ];
    partOf = [
      "podman-compose-arr-root.target"
    ];
    wantedBy = [
      "podman-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
      "WEBUI_PORT" = "9090";
    };
    volumes = [
      "/var/lib/jellyfin/media:/media:rw"
      "/var/lib/qbittorrent/config:/config:rw"
    ];
    ports = [
      "9090:9090/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    labels = {
      "tsdproxy.container_port" = "9090";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "qbittorrent";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=qbittorrent"
      "--network=arr_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arr_default.service"
    ];
    requires = [
      "podman-network-arr_default.service"
    ];
    partOf = [
      "podman-compose-arr-root.target"
    ];
    wantedBy = [
      "podman-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."radarr" = {
    image = "lscr.io/linuxserver/radarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/jellyfin/media:/media:rw"
      "/var/lib/radarr/config:/config:rw"
    ];
    labels = {
      "tsdproxy.container_port" = "7878";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "radarr";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=radarr"
      "--network=arr_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arr_default.service"
    ];
    requires = [
      "podman-network-arr_default.service"
    ];
    partOf = [
      "podman-compose-arr-root.target"
    ];
    wantedBy = [
      "podman-compose-arr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "America/Los_Angeles";
    };
    volumes = [
      "/var/lib/jellyfin/media:/media:rw"
      "/var/lib/sonarr/config:/config:rw"
    ];
    labels = {
      "tsdproxy.container_port" = "8989";
      "tsdproxy.enable" = "true";
      "tsdproxy.name" = "sonarr";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=sonarr"
      "--network=arr_default"
      "--network=tsdproxy_default"
    ];
  };
  systemd.services."podman-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arr_default.service"
    ];
    requires = [
      "podman-network-arr_default.service"
    ];
    partOf = [
      "podman-compose-arr-root.target"
    ];
    wantedBy = [
      "podman-compose-arr-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-arr_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f arr_default";
    };
    script = ''
      podman network inspect arr_default || podman network create arr_default
    '';
    partOf = [ "podman-compose-arr-root.target" ];
    wantedBy = [ "podman-compose-arr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-arr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
